// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Memo = { id: number, title: string, createdAt: bigint, updatedAt: bigint, content: string, };
