// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Memo = { id: number, title: string, created_at: bigint, updated_at: bigint, content: string, };
